### PR TITLE
Updating new sample - msgext-northwind-inventory-action-csharp

### PR DESCRIPTION
**Pull request by Jegadeesh-MSFT**

### CODE REVIEW

**Comment by rabwill** [comment]
Thanks @Jegadeesh-MSFT will take a look soon

**Comment by Jegadeesh-MSFT** [comment]
Hi @rabwill 

I have updated the PR with the necessary code fixes. Could you please review the changes and provide your feedback?

CC: @Wajeed-msft

**Comment by rabwill** [comment]
Hi @Jegadeesh-MSFT ,

I had a quick look, the app works fine as ME actions in Teams but in Copilot it throws error. 
Looks like the issue is in the way the parameters are taken from Copilot action, check this line of code [https://github.com/Jegadeesh-MSFT/Copilot-for-M365-Samples/blob/832a7f286ffe4788ce620aee698055645d2cfbd1/samples/msgext-northwind-inventory-action-csharp/MessageExtensions/AddProductCommand.cs#L4](https://github.com/Jegadeesh-MSFT/Copilot-for-M365-Samples/blob/832a7f286ffe4788ce620aee698055645d2cfbd1/samples/msgext-northwind-inventory-action-csharp/MessageExtensions/AddProductCommand.cs#L41)
You'll need to take the taskParameter object when it is available for Copilot actions to work.

**Comment by Jegadeesh-MSFT** [comment]
> Hi @Jegadeesh-MSFT ,
> 
> I had a quick look, the app works fine as ME actions in Teams but in Copilot it throws error. image
> 
> Looks like the issue is in the way the parameters are taken from Copilot action, check this line of code [https://github.com/Jegadeesh-MSFT/Copilot-for-M365-Samples/blob/832a7f286ffe4788ce620aee698055645d2cfbd1/samples/msgext-northwind-inventory-action-csharp/MessageExtensions/AddProductCommand.cs#L4](https://github.com/Jegadeesh-MSFT/Copilot-for-M365-Samples/blob/832a7f286ffe4788ce620aee698055645d2cfbd1/samples/msgext-northwind-inventory-action-csharp/MessageExtensions/AddProductCommand.cs#L41) You'll need to take the taskParameter object when it is available for Copilot actions to work.
> 
> Similar issue might be there for supplier also so do test in both Teams and Copilot.


Hi @rabwill 

The issue has been fixed. Please find below images,

image

image


Thanks !

**Comment by rabwill** [comment]
Nice one @Jegadeesh-MSFT it works :) Thank you and merging now.

**Pull request merged**
